export { default as Episodes } from './Episodes'
export { default as Characters } from './Characters'
export { default as Planets } from './Planets'
export { default as Species } from './Species'
export { default as Vehicles } from './Vehicles'
export { default as Starships } from './Starships'
export { default as DetailsPage } from './DetailsPage'

export { default as EpisodesDetails } from './EpisodesDetails'
export { default as CharactersDetails } from './CharactersDetails'
export { default as PlanetsDetails } from './PlanetsDetails'
export { default as SpeciesDetails } from './SpeciesDetails'
export { default as VehiclesDetails } from './VehiclesDetails'
export { default as StarshipsDetails } from './StarshipsDetails'

export { default as Navbar } from './Navbar'
export { default as Footer } from './Footer'
export { default as MovieCard } from './MovieCard'
export { default as MainPageLayout } from './MainPageLayout'
export { default as Pagination } from './Pagination'
